// <auto-generated />
namespace BlazorBlog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class migration73487784683684386 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration73487784683684386));
        
        string IMigrationMetadata.Id
        {
            get { return "202010202114585_migration73487784683684386"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
